/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

/**
 *
 * @author Aprendiz
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        LabelNameEMP = new javax.swing.JLabel();
        ButtonAceder = new javax.swing.JButton();
        LabelPass = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        LineaA = new javax.swing.JSeparator();
        LineaB = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        Loginlogo = new javax.swing.JLabel();
        IconoS = new javax.swing.JLabel();
        FondoP = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1250, 788));
        setResizable(false);

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNameEMP.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        LabelNameEMP.setForeground(new java.awt.Color(255, 255, 255));
        LabelNameEMP.setText("NexGenCoders");
        PanelPrincipal.add(LabelNameEMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 760, 150, -1));

        ButtonAceder.setBackground(new java.awt.Color(2, 14, 38));
        ButtonAceder.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 14)); // NOI18N
        ButtonAceder.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAceder.setText("Acceder");
        ButtonAceder.setBorder(new javax.swing.border.MatteBorder(null));
        PanelPrincipal.add(ButtonAceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 110, -1));

        LabelPass.setBackground(new java.awt.Color(255, 255, 255));
        LabelPass.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        LabelPass.setForeground(new java.awt.Color(255, 255, 255));
        LabelPass.setText("Password");
        PanelPrincipal.add(LabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 10));

        LabelUsuario.setFont(new java.awt.Font("Microsoft YaHei", 0, 12)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setText("Usuario");
        PanelPrincipal.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, 20));

        txtUsuario.setBackground(new java.awt.Color(5, 38, 115));
        txtUsuario.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsuario.setCaretColor(new java.awt.Color(51, 0, 51));
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        PanelPrincipal.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 180, 20));

        txtPass.setBackground(new java.awt.Color(4, 31, 98));
        txtPass.setFont(new java.awt.Font("Microsoft PhagsPa", 3, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPass.setCaretColor(new java.awt.Color(4, 31, 98));
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        PanelPrincipal.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 180, 20));
        PanelPrincipal.add(LineaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 303, 180, 10));
        PanelPrincipal.add(LineaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 363, 180, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES LOGIN/Kei.png"))); // NOI18N
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 20, 20));

        Loginlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES LOGIN/Login.png"))); // NOI18N
        PanelPrincipal.add(Loginlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 20, 20));

        IconoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES LOGIN/Logo Sena.png"))); // NOI18N
        PanelPrincipal.add(IconoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        FondoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES LOGIN/FondoP CORREGIDO.png"))); // NOI18N
        PanelPrincipal.add(FondoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 420, 580));

        Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES LOGIN/Fondo GRande.png"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        PanelPrincipal.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1260, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAceder;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoP;
    private javax.swing.JLabel IconoS;
    private javax.swing.JLabel LabelNameEMP;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JSeparator LineaA;
    private javax.swing.JSeparator LineaB;
    private javax.swing.JLabel Loginlogo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
